# Generated by Django 5.1.7 on 2025-03-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
